#!/bin/bash
#
_command_complete() {
    local cur prev
    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD - 1]}
    readarray -d ' ' apps_array < <(find "/etc/swizzin/scripts/install/" -maxdepth 1 -mindepth 1 -type f -printf "%f ")
    readarray -d ' ' upgrade_array < <(find "/etc/swizzin/scripts/upgrade/" -maxdepth 1 -mindepth 1 -type f -printf "%f ")

    case ${COMP_CWORD} in
        1)
            mapfile -t COMPREPLY < <(compgen -W "install remove adduser deluser chpasswd update upgrade panel list" -- "${cur}")
            ;;
        2)
            case ${prev} in
                install)
                    mapfile -t COMPREPLY < <(compgen -W "$(printf "%s " "${apps_array[@]%.*}")" -- "${cur}")
                    ;;
                remove)
                    mapfile -t COMPREPLY < <(compgen -W "$(printf "%s " "${apps_array[@]%.*}")" -- "${cur}")
                    ;;
                upgrade)
                    mapfile -t COMPREPLY < <(compgen -W "$(printf "%s " "${upgrade_array[@]%.*}")" -- "${cur}")
                    ;;
                panel)
                    mapfile -t COMPREPLY < <(compgen -W "fix" -- "${cur}")
                    ;;
                *) ;;

            esac
            ;;
        *)
            COMPREPLY=()
            ;;
    esac
}
complete -F _command_complete box
