#!/bin/bash
#
# ln -fs /etc/swizzin/sources/bash_completion/swizzin /etc/bash_completion.d/swizzin
#
_command_complete() {
    local cur sub_cmd
    cur=${COMP_WORDS[COMP_CWORD]}
    sub_cmd=${COMP_WORDS[1]}

    mapfile -t install_array < <(find "/etc/swizzin/scripts/install/" -type f -exec basename {} \; | sort)
    mapfile -t remove_array < <(find "/etc/swizzin/scripts/remove/" -type f -exec basename {} \; | sort)
    mapfile -t upgrade_array < <(find "/etc/swizzin/scripts/upgrade/" -type f -exec basename {} \; | sort)

    case ${COMP_CWORD} in
        1)
            mapfile -t COMPREPLY < <(compgen -W "install it remove rm adduser deluser chpasswd update upgrade rtx rmgrsec list help test" -- "${cur}")
            ;;
        *)
            case ${sub_cmd} in
                install | it)
                    mapfile -t COMPREPLY < <(compgen -W "$(printf "%s " "${install_array[@]%.*}")" -- "${cur}")
                    ;;
                remove | rm)
                    mapfile -t COMPREPLY < <(compgen -W "$(printf "%s " "${remove_array[@]%.*}")" -- "${cur}")
                    ;;
                upgrade)
                    mapfile -t COMPREPLY < <(compgen -W "$(printf "%s " "${upgrade_array[@]%.*}")" -- "${cur}")
                    ;;
                *) ;;
            esac
            ;;
    esac
}
# complete -o nosort -F _command_complete box
complete -F _command_complete box
