#!/bin/bash
#
# ln -fs /etc/swizzin/sources/bash_completion/swizzin /etc/bash_completion.d/swizzin
#
_command_complete() {
    local cur prev
    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD - 1]}

    readarray -t apps_array < <(cat '/var/lib/swizzin/db/bash_completion/apps.list')
    readarray -t upgrade_array < <(cat '/var/lib/swizzin/db/bash_completion/upgrade.list')

    case ${COMP_CWORD} in
        1)
            mapfile -t COMPREPLY < <(compgen -W "install remove adduser deluser chpasswd update upgrade rtx rmgrsec list help" -- "${cur}")
            ;;
        2)
            case ${prev} in
                install)
                    mapfile -t COMPREPLY < <(compgen -W "$(printf "%s " "${apps_array[@]%.*}")" -- "${cur}")
                    ;;
                remove)
                    mapfile -t COMPREPLY < <(compgen -W "$(printf "%s " "${apps_array[@]%.*}")" -- "${cur}")
                    ;;
                upgrade)
                    mapfile -t COMPREPLY < <(compgen -W "$(printf "%s " "${upgrade_array[@]%.*}")" -- "${cur}")
                    ;;
                *) ;;

            esac
            ;;
        *)
            COMPREPLY=()
            ;;
    esac
}
# complete -o nosort -F _command_complete box
complete -F _command_complete box
