#! /bin/bash
# Ensures that dependencies are installed and corrects them if that is not the case.
log="/root/logs/swizzin.log"
#space-separated list of required GLOBAL SWIZZIN dependencies (NOT application specific ones)
dependencies="jq sl"

# shellcheck source=sources/functions/apt
. /etc/swizzin/sources/functions/apt

missing=""
for dep in $dependencies; do
    if ! _check_installed "$dep"; then 
        missing+="$dep "
    fi
done

if [[ $missing != "" ]]; then 
    echo "Installing the following dependencies: $missing"
    _apt_install_default "$missing"
fi