#!/bin/bash
#Disk Widget Switcher root <-> home
if [[ -f /srv/panel/db/.smoked.lock ]]; then theme=smoked; else theme=defaulted; fi

if [[ -z $1 ]]; then
  echo "You must specify root or home"
  exit 1
fi

if [[ $1 == "home" ]]; then
  rm -f /srv/panel/widgets/disk_data.php
  cp /srv/panel/themes/${theme}/widgets/disk_datah.php /srv/panel/widgets/disk_data.php
elif [[ $1 == "root" ]]; then
  rm -f /srv/panel/widgets/disk_data.php
  cp /srv/panel/themes/${theme}/widgets/disk_data.php /srv/panel/widgets/disk_data.php
else
  echo "You must specify root or home"
  exit 1
fi

service nginx reload
/usr/local/bin/swizzin/php-fpm-cli -r 'opcache_reset();'