#!/bin/bash
. /etc/swizzin/sources/functions/users
apt_install libxml2-utils
user=$(_get_master_username)
function _get_sonarr_vars() {
    if [[ -f /install/.sonarr.lock ]]; then
        echo_progress_start "Found Sonarr. Grabbing config."
        # Grab config deets from xml
        export s_address=$(xmllint --xpath "//Config/BindAddress/text()" /home/${user}/.config/sonarr/config.xml)
        export s_port=$(xmllint --xpath "//Config/Port/text()" /home/${user}/.config/sonarr/config.xml)
        export s_base=$(xmllint --xpath "//Config/UrlBase/text()" /home/${user}/.config/sonarr/config.xml)
        export s_key=$(xmllint --xpath "//Config/ApiKey/text()" /home/${user}/.config/sonarr/config.xml)
        echo_progress_done "Grabbed Sonarr config."
    else
        export s_port="8989"
    fi
}

function _get_radarr_vars() {
    if [[ -f /install/.radarr.lock ]]; then
        echo_progress_start "Found Radarr. Grabbing config."
        # Grab config deets from xml
        export r_address=$(xmllint --xpath "//Config/BindAddress/text()" /home/${user}/.config/Radarr/config.xml)
        export r_port=$(xmllint --xpath "//Config/Port/text()" /home/${user}/.config/Radarr/config.xml)
        export r_base=$(xmllint --xpath "//Config/UrlBase/text()" /home/${user}/.config/Radarr/config.xml)
        export r_key=$(xmllint --xpath "//Config/ApiKey/text()" /home/${user}/.config/Radarr/config.xml)
        echo_progress_done "Radarr config has been retrieved."
    else
        export r_port="7878"
    fi
}
