#!/bin/bash

function check_debian_backports () {
    codename=$(lsb_release -cs)
    if grep -q "${codename}-backports" /etc/apt/sources.list; then
        echo "Debian ${codename} backports already enabled.
    else
        echo "Enabling Debian ${codename} backports repository"
        echo "deb http://ftp.debian.org/debian ${codename}-backports main" >> /etc/apt/sources.list
        echo "deb-src deb http://ftp.debian.org/debian ${codename}-backports main" >> /etc/apt/sources.list
        apt-get -y -q update > /dev/null 2>&1
    fi
}