#!/bin/bash
if [ -z "$CALIBRE_LIBRARY_USER" ]; then
    if ! CALIBRE_LIBRARY_USER="$(swizdb get calibre/library_user)"; then
        CALIBRE_LIBRARY_USER=$(_get_master_username)
    fi
fi

if [ -z "$CALIBRE_LIBRARY_PATH" ]; then
    if ! CALIBRE_LIBRARY_PATH="$(swizdb get calibre/library_path)"; then
        CALIBRE_LIBRARY_PATH="/home/$CALIBRE_LIBRARY_USER/Calibre Library"
    fi
fi

calibrecs_usrmgr() {
    echo_log_only "Calibrecs User Manager $@"
    calibre_server_config_path="/home/$CALIBRE_LIBRARY_USER/.config/calibrecs"
    calibre-server --userdb "$calibre_server_config_path"/server-users.sqlite --manage-users -- "$@"
    ret=$?
    chown -R "$CALIBRE_LIBRARY_USER": "$calibre_server_config_path"
    return $ret
}
