#!/bin/bash

debug() {
    journalctl -e -u "${1}" | ccze -Ao nolookups
}

debug_user() {
    journalctl -e --user -u "${1}" | ccze -Ao nolookups
}

_pipe_status() {
    if [[ "${PIPESTATUS[0]}" -gt '0' ]]; then
        echo_error "Error: The function produced an exit code greater than 0 - Check the logs"
        exit "${PIPESTATUS[0]}"
    fi
}
