#!/bin/bash

function whiptail_deluge () {
  if [[ -z $deluge ]]; then
    function=$(whiptail --title "Install Software" --menu "Choose a Deluge version:" --ok-button "Continue" --nocancel 12 50 3 \
                Repo "" \
                1.3 "" \
                2.0 "" 3>&1 1>&2 2>&3)

    if [[ $function == Repo ]]; then
      export deluge=repo
    elif [[ $function == 1.3 ]]; then
      export deluge=1.3-stable
    elif [[ $function == 2.0 ]]; then
      export deluge=master
    fi
  fi
}

function whiptail_libtorrent_rasterbar () {
  if [[ -z $libtorrent ]]; then
    if [[ ! $deluge == master ]]; then
      function=$(whiptail --title "Install Software" --menu "Choose a libtorrent branch:" --ok-button "Continue" --nocancel 12 50 3 \
                  Repo "" \
                  1.0 "" \
                  1.1 "" 3>&1 1>&2 2>&3)
    else
      function=$(whiptail --title "Install Software" --menu "Choose a libtorrent branch:" --ok-button "Continue" --nocancel 12 50 3 \
                  Repo "" \
                  1.0 "" \
                  1.1 "" \
                  1.2 "" 3>&1 1>&2 2>&3)
    fi

    if [[ $function == Repo ]]; then
      export libtorrent=repo
    elif [[ $function == 1.0 ]]; then
      export libtorrent=RC_1_0
    elif [[ $function == 1.1 ]]; then
      export libtorrent=RC_1_1
    elif [[ $function == 1.2 ]]; then
      export libtorrent=RC_1_2
    fi
  fi
}

function remove_ltcheckinstall () {
  oldv=$(apt-cache show libtorrent | grep checkinstall)
  if [[ -n $oldv ]]; then
    echo "Removing checkinstall libtorrent"
    dpkg -r libtorrent
  fi
}

function build_libtorrent_rasterbar () {
  release=$(lsb_release -cs)
  . /etc/swizzin/sources/functions/fpm

  if [[ $libtorrent = "repo" ]]; then
      case $release in
          "jessie")
          apt-get install -y -q libtorrent-rasterbar7
          ;;
          "xenial")
          apt-get install -y -q libtorrent-rasterbar8
          ;;
          *)
          apt-get install -y -q libtorrent-rasterbar9
          ;;
      esac
  else
    LTRC=$libtorrent
    LIST='build-essential libtool libboost-system-dev libboost-python-dev libssl-dev libgeoip-dev libboost-chrono-dev libboost-random-dev
    geoip-database'
    for depend in $LIST; do
      apt-get -qq -y install $depend >>"${log}" 2>&1 || { echo "ERROR: APT-GET could not install a required package: ${depend}. That's probably not good..."; }
    done
    install_fpm
    #OpenSSL 1.1.0 might fk a lot of things up -- Requires at least libboost-1.62 to build
    #if [[ ! ${codename} =~ ("xenial")|("yakkety") ]]; then
    #  LIST='libboost-system-dev libboost-python-dev libssl-dev libgeoip-dev libboost-chrono-dev libboost-random-dev'
    #  for depend in $LIST; do
    #    apt-get -qq -y install $depend >>"${log}" 2>&1
    #  done
    #else
    #  cd /tmp
    #  wget https://sourceforge.net/projects/boost/files/boost/1.62.0/boost_1_62_0.tar.gz
    #  tar xf boost_1_62_0.tar.gz
    #  cd boost_1_62_0
    #  ./bootstrap.sh --prefix=/usr
    #  ./b2 install
    #fi

    cd /tmp
    git clone -b ${LTRC} https://github.com/arvidn/libtorrent.git >>"${log}" 2>&1
    cd libtorrent
    ./autotool.sh >>"${log}" 2>&1
    ./configure --enable-python-binding --with-lib-geoip --with-libiconv >>"${log}" 2>&1
    VERSION=$(grep -i package_version\ \= /tmp/libtorrent/Makefile | cut -d= -f2 | sed 's/ //g')
    make -j$(nproc) >>"${log}" 2>&1

    make DESTDIR=/tmp/dist/libtorrent install > /dev/null 2>&1
    mv /tmp/dist/libtorrent/usr/local/lib/python2.7/site-packages /tmp/dist/libtorrent/usr/local/lib/python2.7/dist-packages
    mkdir -p /root/dist
    fpm -f -C /tmp/dist/libtorrent -p /root/dist/libtorrent-rasterbar_VERSION.deb -s dir -t deb -n libtorrent-rasterbar --version ${VERSION} --description "Libtorrent rasterbar compiled by swizzin" > /dev/null 2>&1
    #checkinstall -y --pkgversion=${LTRC} >>"${log}" 2>&1
    dpkg -i /root/dist/libtorrent-rasterbar_${VERSION}.deb
    ldconfig
    cd /tmp
    rm -r libtorrent
    rm -r /tmp/dist
  fi
  if [[ ! -f /install/.libtorrent.lock ]]; then touch /install/.libtorrent.lock; fi
}

function build_deluge () {
  if [[ $deluge == repo ]]; then
    apt-get -q -y update >>"${log}" 2>&1
    apt-get -q -y install deluged deluge-web deluge-console >>"${log}" 2>&1
    
    chmod 644 /etc/swizzin/scripts/deluge.UpdateTracker.py
    cp /etc/swizzin/scripts/deluge.UpdateTracker.py /usr/lib/python2.7/dist-packages/deluge/ui/console/commands/update-tracker.py
    
    systemctl stop deluged
    update-rc.d deluged remove
    rm /etc/init.d/deluged
  else
    case $deluge in
      master)
        LIST='python3 python3-setuptools python3-zope.interface python3-twisted python3-openssl python3-xdg python3-chardet python3-pygame python3-mako python3-setproctitle python3-rencode python3-pil'
        pythonver=python3
        distver=python3
        args="--python-disable-dependency=pyxdg --python-disable-dependency=pyopenssl -d python3-openssl -d python3-xdg"
      ;;
      1.3-stable)
        LIST='python python-twisted python-openssl python-setuptools intltool python-xdg python-chardet geoip-database python-notify python-pygame python-glade2 librsvg2-common xdg-utils python-mako'
        pythonver=python2
        distver=python2.7
        args=
      ;;
    esac
    for depend in $LIST; do
      apt-get -qq -y install $depend >>"${log}" 2>&1 || { echo "ERROR: APT-GET could not install a required package: ${depend}. That's probably not good..."; }
    done
    . /etc/swizzin/sources/functions/fpm
    install_fpm
    cd /tmp
    git clone -b ${deluge} git://deluge-torrent.org/deluge.git >>"${log}" 2>&1
    cd deluge
    VERSION=$(git describe | cut -d- -f2)
    mkdir -p /root/dist
    fpm ${args} --python-fix-dependencies --python-bin=${pythonver} --python-package-name-prefix=${pythonver} --python-setup-py-arguments=--install-layout=deb -n deluge-common -f -p /root/dist/deluge-common_VERSION.deb --description "Deluge compiled by swizzin" -s python -t deb /tmp/deluge/setup.py > /dev/null 2>&
    dpkg -i /root/dist/deluge-common_${VERSION}.deb
    chmod 644 /etc/swizzin/scripts/deluge.UpdateTracker.py
    cp /etc/swizzin/scripts/deluge.UpdateTracker.py "/usr/lib/${distver}/dist-packages/deluge/ui/console/commands/update-tracker.py"
    cd /tmp
    rm -rf deluge
    apt-mark hold deluge-common
  fi
}

function ltconfig () {
  dver=$(deluged -v | grep deluged | awk '{print $2}' | sed 's/.dev0//'g)
  mkdir -p /etc/skel/.config/deluge/plugins
  case $dver in
    1.3*)
      ltcver=0.3.1-py2.7
      py=-py2.7
      if ls /etc/skel/.config/deluge/plugins/ltConfig-2* > /dev/null 2>&1; then rm -f /etc/skel/.config/deluge/plugins/ltConfig-2*; fi
      if ls /home/${u}/.config/deluge/plugins/ltConfig-2* > /dev/null 2>&1; then rm -f /home/${u}/.config/deluge/plugins/ltConfig-2*; fi
    ;;
    2.0*)
      ltcver=2.0.0
      py=
      if [[ -f /etc/skel/.config/deluge/plugins/ltConfig-0.3.1-py2.7.egg ]]; then rm -f /etc/skel/.config/deluge/plugins/ltConfig-0.3.1-py2.7.egg; fi
      if [[ -f /home/${u}/.config/deluge/plugins/ltConfig-0.3.1-py2.7.egg ]]; then rm -f /home/${u}/.config/deluge/plugins/ltConfig-0.3.1-py2.7.egg; fi
    ;;
  esac
  if [[ ! -f /etc/skel/.config/deluge/plugins/ltConfig-${ltcver}${py}.egg ]]; then
    cd /etc/skel/.config/deluge/plugins/
    wget -q https://github.com/ratanakvlun/deluge-ltconfig/releases/download/v${ltcver}/ltConfig-${ltcver}${py}.egg
  fi
  mkdir -p /home/${u}/.config/deluge/plugins
  if [[ ! -f /home/${u}/.config/deluge/plugins/ltConfig-${ltcver}${py}.egg ]]; then
    cd /home/${u}/.config/deluge/plugins/
    wget -q https://github.com/ratanakvlun/deluge-ltconfig/releases/download/v${ltcver}/ltConfig-${ltcver}${py}.egg
    chown $u: /home/${u}/.config/deluge/plugins/ltConfig-${ltcver}${py}.egg
  fi
}