#!/bin/bash

download_theme() {
    theme_url="https://github.com/Naereen/Nginx-Fancyindex-Theme/archive/ee2e73c8dd1584b84ddad0cfcc44fbd903bdccd8.zip"
    wget -q $theme_url -O /tmp/fancyindex.tar.gz
    mkdir -p /tmp/fancyindex
    tar -xzf /tmp/fancyindex.tar.gz -C /tmp/fancyindex --strip-components=1
    mv /tmp/fancyindex/Nginx-Fancyindex /srv/fancyindex

    # fix refs
    sed -i 's/href="\/[^\/]*/href="\/fancyindex/g' /srv/fancyindex/header.html
    sed -i 's/src="\/[^\/]*/src="\/fancyindex/g' /srv/fancyindex/footer.html
}

cat_config() {
    cat > /etc/nginx/snippets/fancyindex.conf << FIC
    fancyindex on;
    fancyindex_localtime on;
    fancyindex_exact_size off;
    fancyindex_header "/fancyindex/header.html";
    fancyindex_footer "/fancyindex/footer.html";
    fancyindex_name_length 255; # Maximum file name length in bytes, change as you like.
FIC
}
