#!/bin/bash

function install_fpm() {
    fpm -h > /dev/null 2>&1
    exit=$?
    if [[ ! $exit == '0' ]]; then
        apt_install ruby ruby-dev libffi-dev
        echo_progress_start "Installing fpm through ruby/gem"
        case $(_os_codename) in
            buster)
                gem install public_suffix -v 4.0.7 >> $log 2>&1
                ;;
            *) ;;
        esac
        gem install fpm >> $log 2>&1
        echo_progress_done
    fi
}
