#!/bin/bash
# Upgrade to GCC 12 for Jammy users to unlock better performance of compiled software

GCC_Jammy_Upgrade() {
    # Check if the operating system is Ubuntu 22.04 LTS
    if [[ $(_os_codename) == "jammy" ]]; then
        # Check if GCC 12 is installed by looking for the binary path
        if ! which gcc-12 > /dev/null; then
            echo_info "Installing GCC 12"
            apt_install gcc-12 g++-12
        fi
        # Check if GCC 12 is system default by comparing the version string
        if [[ $(gcc --version | grep -c "Ubuntu 12") -le 0 ]]; then
            echo_info "Configuring GCC 12"
            echo_log_only "Removing all GCC preferences"
            update-alternatives --remove-all gcc >> $log 2>&1
            update-alternatives --remove-all g++ >> $log 2>&1
            echo_log_only "Setting GCC 12 as system default"
            update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 12 >> $log 2>&1
            update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 12 >> $log 2>&1
            if which gcc-11 > /dev/null; then
                echo_log_only "Setting GCC 11 as system backup"
                update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 11 >> $log 2>&1
                update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 11 >> $log 2>&1
            fi
        fi
    fi
}
