#!/bin/bash
install_java8() {
    codename=$(_os_codename)
    distribution=$(_os_distro)
    if [[ $distribution == "ubuntu" ]]; then
        apt_install openjdk-8-jre
    elif [[ $distribution == "debian" ]]; then
        case $codename in
            "stretch")
                apt_install openjdk-8-jre
                ;;
            *)
                echo_progress_start "Adding adoptopenjdk repository"
                curl -s https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | gpg --dearmor > /usr/share/keyrings/adoptopenjdk-archive-keyring.gpg 2>> "${log}"
                echo "deb [signed-by=/usr/share/keyrings/adoptopenjdk-archive-keyring.gpg] https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ ${codename} main" > /etc/apt/sources.list.d/adoptopenjdk.list
                echo_progress_done "adoptopenjdk repos enabled"
                apt_update
                apt_install adoptopenjdk-8-hotspot
                ;;
        esac
    fi
}
