#!/bin/bash
install_java8() {
    codename=$(_os_codename)
    distribution=$(_os_distro)
    if [[ $distribution == "ubuntu" ]]; then
        apt_install openjdk-8-jre
    elif [[ $distribution == "debian" ]]; then
        case $codename in
            *)
                echo_progress_start "Adding temurin repository"
                curl -s https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --dearmor > /usr/share/keyrings/temurin-archive-keyring.gpg 2>> "${log}"
                echo "deb [signed-by=/usr/share/keyrings/temurin-archive-keyring.gpg] https://packages.adoptium.net/artifactory/deb/ ${codename} main" > /etc/apt/sources.list.d/temurin.list
                echo_progress_done "temurin repos enabled"
                apt_update
                apt_install temurin-8-jdk
                ;;
        esac
    fi
}
