#!/bin/bash
install_java8() {
    codename=$(_os_codename)
    distribution=$(_os_distro)
    if [[ $distribution == "ubuntu" ]]; then
        apt_install openjdk-8-jre
    elif [[ $distribution == "debian" ]]; then
        case $codename in
            "stretch")
                apt_install openjdk-8-jre
                ;;
            *)
                echo_progress_start "Adding adoptopenjdk repository"
                apt_install software-properties-common
                wget -qO- https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key --keyring /etc/apt/trusted.gpg.d/adoptopenjdk.gpg add - >> "${log}" 2>&1
                add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ >> "${log}" 2>&1
                echo_progress_done "adoptopenjdk repos enabled"
                apt_update
                apt_install adoptopenjdk-8-hotspot
                ;;
        esac
    fi
}
