#!/usr/bin/env bash

# The directory where locks are stored
#\
# **DO NOT USE THIS OUTSIDE OF MAYBE LIKE BOX AND THE UPDATE FUNCTION PERIOD**
export lockdir="/var/lock/swizzin"

# Records and application as installed
# \
# $1 = app name
lock() {
    mkdir -p "$lockdir"
    touch "$lockdir"/"$1"
}
export -f lock

# Removes an application from the list of locks
# \
# $1 = app name
unlock() {
    rm "$lockdir"/"$1" >> "$log" 2>&1
    return $?
}
export -f unlock

# Returns exit code indicating if app is installed or not
# \
# $1 = app name
islocked() {
    [[ -e "$lockdir"/"$1" ]]
    return $?
}
export -f islocked

# Returns a newline separated list of installed applications
locklist() {
    find "$lockdir" -type f --maxdepth 1
    return $?
}
export -f locklist

# Returns the full path of the **possible** lock file
# \
# **Returns code 1 if it does not exist yet**
lockpath() {
    echo "$lockdir/$1"
    islocked "$1" || return 1
}
