#!/usr/bin/env bash

install_logrotate() {
    apt_install logrotate
    mkdir -p /etc/lorgotate.d
    if ! grep -q "include /etc/logrotate.d" /etc/logrotate.conf; then
        echo_log_only "Adding logrotate.d to conf"
        echo "include /etc/logrotate.d" >> /etc/logrotate.conf
    fi

    cat > /etc/logrotate.d/swizzin << EOF
/root/logs/swizzin.log {
    weekly
    missingok
    nocompress
    notifempty
}
EOF

}
