#!/bin/bash

function mono_repo_setup () {
  distribution=$(lsb_release -is)
  codename=$(lsb_release -cs)
  if [[ ! -f /etc/apt/sources.list.d/mono-xamarin.list ]]; then
    if [[ $distribution == "Ubuntu" ]]; then
      apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF >/dev/null 2>&1
    elif [[ $distribution == "Debian" ]]; then
      if [[ ! $codename == "buster" ]]; then
        apt-key --keyring /etc/apt/trusted.gpg.d/mono-xamarin.gpg adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF > /dev/null 2>&1
        #gpg --keyserver http://keyserver.ubuntu.com --recv 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF >/dev/null 2>&1
        #gpg --export 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF > /etc/apt/trusted.gpg.d/mono-xamarin.gpg
      fi
    fi
    if [[ ! $codename =~ ("buster"|"focal") ]]; then
      echo "deb https://download.mono-project.com/repo/${distribution,,} ${codename}/snapshots/5.18/. main" > /etc/apt/sources.list.d/mono-xamarin.list
    fi
  fi
}

function mono_repo_update () {
  distribution=$(lsb_release -is)
  codename=$(lsb_release -cs)
  if [[ -f /etc/apt/sources.list.d/mono-xamarin.list ]]; then
    if grep -q "5.18" /etc/apt/sources.list.d/mono-xamarin.list; then
      :
    else
      echo "deb https://download.mono-project.com/repo/${distribution,,} ${codename}/snapshots/5.18/. main" > /etc/apt/sources.list.d/mono-xamarin.list
      echo "Upgrading to mono 5.18 snapshot"
      
      fuckmono=()

      #for i in ${PACKAGES[@]}; do
      #  fuckmono+=(${i}/${codename})
      #done

      apt-get -y -q update
      apt-get -y -q upgrade
      #apt-get install -q -y --allow-downgrades ${fuckmono[@]} || apt-get install -q -y --force-yes ${fuckmono[@]}
      apt-get -y -q autoremove
    fi
  #elif [[ $codename == "buster" ]]; then
  #  :
  else
    if ! command -v mono > /dev/null 2>&1 ; then
      mono_repo_setup
      apt-get -y -q update
      apt-get -y -q install mono-complete
      apt-get -y -q upgrade
    fi
  fi
}