#!/bin/bash

function navidrome_download_latest() {
    echo_progress_start "Downloading release archive"

    case "$(_os_arch)" in
        "amd64") arch='x86_64' ;;
        "arm64") arch="arm64" ;;
        "armhf") arch="armv6" ;;
        *)
            echo_error "Arch not supported"
            exit 1
            ;;
    esac

    latest=$(curl -sL https://api.github.com/repos/navidrome/navidrome/releases/latest | grep "Linux_$arch" | grep browser_download_url | cut -d \" -f4) || {
        echo_error "Failed to query GitHub for latest version"
        exit 1
    }

    if ! curl "$latest" -L -o "/tmp/navidrome.tar.gz" >> "$log" 2>&1; then
        echo_error "Download failed, exiting"
        exit 1
    fi
    echo_progress_done "Archive downloaded"

    echo_progress_start "Extracting archive"

    
    tar xfv "/tmp/navidrome.tar.gz" --directory /opt/navidrome/ >> "$log" 2>&1 || {
        echo_error "Failed to extract"
        exit 1
    }
    rm -rf "/tmp/navidrome.tar.gz"
    echo_progress_done "Archive extracted"
}
