#! /bin/bash
# flying_sausages 2020 for swizzin
# Some stuff for nextcloud

#Passes a command to the nextcloud OCC command
function _occ() {
    torun="$1"
    echo_log_only "Passing \"${torun}\" to occ"
    su -s /bin/sh www-data -c "php /srv/nextcloud/occ ${torun}" >> "$log" 2>&1
}
