#!/bin/bash
#npm related functions


function npm_install() {
  if [[ ! -f /etc/apt/sources.list.d/nodesource.list ]]; then
    bash <(curl -sL https://deb.nodesource.com/setup_12.x) >> $log 2>&1
  elif [[ -f /etc/apt/sources.list.d/nodesource.list ]]; then
    npm_update
  fi

  if [[ ! $(command -v npm) ]]; then
    apt-get -y -q install nodejs build-essential >> $log 2>&1
  fi
}

function npm_update() {
  if [[ -f /etc/apt/sources.list.d/nodesource.list ]]; then
    if ! grep -q 12 /etc/apt/sources.list.d/nodesource.list; then
      echo "Upgrading nodejs to version 12 LTS"
      bash <(curl -sL https://deb.nodesource.com/setup_12.x) >> $log 2>&1
      apt -y -q  update  >> $log 2>&1
      apt -y -q upgrade  >> $log 2>&1
    fi
  fi
}