#!/bin/bash
#npm related functions

function npm_install() {
    if [[ ! -f /etc/apt/sources.list.d/nodesource.list ]]; then
        apt_update
        apt_install ca-certificates curl gnupg
        mkdir -p /etc/apt/keyrings
        curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
        NODE_MAJOR=20
        echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
        apt_update
        apt_install nodejs
    elif [[ -f /etc/apt/sources.list.d/nodesource.list ]]; then
        npm_update
    fi

    if [[ ! $(command -v npm) ]]; then
        echo_progress_start "Installing npm"
        apt_install nodejs build-essential
        echo_progress_done "Npm installed"
    fi
}

function npm_update() {
    if [[ -f /etc/apt/sources.list.d/nodesource.list ]]; then
        if [[ $(grep -m1 -oP 'node_\d+' /etc/apt/sources.list.d/nodesource.list | sed 's/node_//g') -lt "20" ]]; then
            echo_progress_start "Upgrading nodejs to version 20 LTS"
            apt_update
            apt_install ca-certificates curl gnupg
            mkdir -p /etc/apt/keyrings
            curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
            NODE_MAJOR=20
            echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
            apt_update
            apt_upgrade
            echo_progress_done "Npm upgraded"
        fi
    fi
}

function yarn_install() {
    npm_install
    echo_progress_start "Installing yarn"
    npm install --quiet --global yarn >> $log 2>&1
    echo_progress_done "Yarn installed"
}
