#!/bin/bash

function _download() {
    echo_progress_start "Downloading install script"
    cd /tmp
    wget https://nzbget.com/download/nzbget-latest-bin-linux.run >> $log 2>&1
    echo_progress_done
}

function _get_noexec() {
    noexec=$(grep "/tmp" /etc/fstab | grep noexec)

    if [[ -n $noexec ]]; then
        mount -o remount,exec /tmp
        noexec=1
    fi
}

function _service() {
    echo_progress_start "Installing systemd service"
    cat > /etc/systemd/system/nzbget@.service << NZBGD
[Unit]
Description=NZBGet Daemon
Documentation=http://nzbget.com/Documentation
After=network.target

[Service]
User=%i
Group=%i
Type=forking
ExecStart=/bin/sh -c "/home/%i/nzbget/nzbget -D"
ExecStop=/bin/sh -c "/home/%i/nzbget/nzbget -Q"
ExecReload=/bin/sh -c "/home/%i/nzbget/nzbget -O"
Restart=on-failure

[Install]
WantedBy=multi-user.target
NZBGD
    echo_progress_done
}
