#!/bin/bash
set +x

organizr_formkey() {
    hash_key=$(grep -i hash /root/.organizr | cut -d= -f2 | tr -d ' ')
    php -r "echo password_hash(substr(\"$hash_key\", 2, 10), PASSWORD_BCRYPT);"
}

organizr_adduser() {
    formKey=$(organizr_formkey)
    curl --location --request POST 'https://127.0.0.1/organizr/api/v2/users' \
        --header 'content-type: application/x-www-form-urlencoded' \
        --header 'charset: UTF-8' \
        --header 'Content-Encoding: gzip' \
        --header 'Content-Type: application/x-www-form-urlencoded' \
        --data-urlencode "username=$1" \
        --data-urlencode "email=$2" \
        --data-urlencode "password=$3" \
        --data-urlencode "formKey=${formKey}" \
        -sk >> $log 2>&1
}
