#!/bin/bash

_os_distro() {
    source /etc/os-release
    printf '%s' "$ID"
}
export -f _os_distro

_os_codename() {
    source /etc/os-release
    printf '%s' "$VERSION_CODENAME"
}
export -f _os_codename

_os_arch() {
    dpkg --print-architecture
}
export -f _os_arch
