#!/bin/bash

# Returns the distribution of the device as seen in `/etc/os-release`.
# \
# Output examples:
# - `ubuntu`
# - `debian`
# - `raspbian`
_os_distro() {
    source /etc/os-release
    printf '%s' "$ID"
}
export -f _os_distro

# Returns the codename of the device as seen in `/etc/os-release`.
# \
# Output examples:
# - `focal`
# - `buster`
# - `stretch`
# - etc.
_os_codename() {
    source /etc/os-release
    output=$VERSION_CODENAME
    
    # Add support for Linux Mint, by returning the UBUNTU_CODENAME instead
    # Supports all flavours of Ubuntu returning 'focal' or 'jammy'
    mint=("vera" "vanessa" "una" "uma" "ulyssa" "ulyana" "tricia" "tina" "tessa" "tara")
    for str in ${mint[@]}; do
        if [[ "$output" == "$str" ]]; then
            output=$UBUNTU_CODENAME
            break
        fi
    done
    
    printf '%s' "$output"
}
export -f _os_codename

# Returns the architecture of the device as interpreted by `dpkg`.
# \
# Possible output is one of the following:
# - `amd64` (x86_64 essentially)
# - `arm64`
# - `armhf`
_os_arch() {
    dpkg --print-architecture
}
export -f _os_arch
