#!/bin/bash

if [[ -f /tmp/.install.lock ]]; then
  export log="/root/logs/install.log"
else
  log="/root/logs/swizzin.log"
fi

#Gets the version nginx is using and restarts it
function restart_php_fpm () {
    version=$(php_service_version)
    serv="php${version}-fpm.service"
    echo "Restarting $serv" | tee -a $log
    #serv=(ls /etc/systemd/system | grep php7 | tail -1)
    systemctl restart $serv >> $log 2>&1
}

function reload_php_fpm () {
    version=$(php_service_version)
    serv="php${version}-fpm.service"
    echo "Reloading $serv" | tee -a $log
    #serv=(ls /etc/systemd/system | grep php7 | tail -1)
    systemctl reload $serv >> $log 2>&1
}

function reload_php_opcache (){
    echo "Reloading OPcache"
    /usr/local/bin/swizzin/php-fpm-cli -r 'opcache_reset() ?>';
}

# function disable_other_phps () {
#     #TODO
# }

#Returns for example '7.4'
function php_v_from_nginxconf () { 
    nginxconfpath='/etc/nginx/sites-enabled/default'
    version=$(cat $nginxconfpath | grep -o -P '(?<=/php/php).*(?=-fpm.sock)')
    echo "${version}"
}

#returns for example '7.4'
function php_service_version () {
    echo "$(ls /lib/systemd/system | grep php | grep fpm | sort | tail -1 | grep -o -P '(?<=php).*(?=-fpm)')"
}




