#!/bin/bash

# Install fuse
function _fuse() {
    apt_install fuse
    sed -i -e 's/#user_allow_other/user_allow_other/' /etc/fuse.conf
}

function _rclone_download_latest() {
    echo_progress_start "Downloading and installing rclone"
    # One-liner to check arch/os type, as well as download latest rclone for relevant system.
    wget -q https://rclone.org/install.sh -O /tmp/rcloneinstall.sh >>"${log}" 2>&1

    # Make sure rclone downloads and installs without error before proceeding
    if ! bash /tmp/rcloneinstall.sh; then
        echo_error "Rclone installer failed"
        exit 1
    fi
    echo_progress_done
}
