#!/bin/bash

#Log is required for checking for failures
if [[ -z $log ]]; then export log="/root/logs/swizzin.log"; fi

function shinkro_download_latest() {
    echo_progress_start "Downloading shinkro release archive"

    case "$(_os_arch)" in
        "amd64") arch='amd64' ;;
        "arm64") arch="arm64" ;;
        "armhf") arch="armv6" ;;
        *)
            echo_error "Arch not supported"
            exit 1
            ;;
    esac

    latest=$(curl -sL https://api.github.com/repos/varoOP/shinkro/releases/latest | grep "linux_$arch" | grep browser_download_url | grep ".tar.gz" | cut -d \" -f4) || {
        echo_error "Failed to query GitHub for latest version"
        exit 1
    }

    if ! curl "$latest" -L -o "/tmp/shinkro.tar.gz" >> "$log" 2>&1; then
        echo_error "Download failed, exiting"
        exit 1
    fi
    echo_progress_done "Archive downloaded"

    echo_progress_start "Extracting archive"

    tar xfv "/tmp/shinkro.tar.gz" --directory /usr/bin/ >> "$log" 2>&1 || {
        echo_error "Failed to extract"
        exit 1
    }
    rm -rf "/tmp/shinkro.tar.gz"
    echo_progress_done "Archive extracted"
}
