#!/bin/bash

# Creates directories from a file within a user directory
# Accepts the user as an argument as the variables for that are not standard in swizzin
function _make_custom_user_dirs () {
    arg_user="$1"
    export custom_dirs_made=false

    dirfile='/etc/swizzin/conf/conf.d/userdirstomake'
    #Appending a white line to the dirfile in case the last line didn't have a linebreaker
    #TODO see if this is the right thing to do
    echo "" >> $dirfile
    if [[ -f "$dirfile" ]]; then
        echo "Creating custom user directories for $arg_user"
        while IFS= read -r line
        do
            folder=$(echo "$line" | awk '{$1=$1};1' )
            if [[ -n "$folder" ]]; then 
                fulldirpath="/home/${arg_user}/${folder}"
                mkdir -p "$fulldirpath"
                chown -R "$arg_user":"$arg_user" "$fulldirpath"
                chmod 755 "$fulldirpath"
            fi
        done <"$dirfile"
        export custom_dirs_made=true
    fi
}