#!/usr/bin/env bash
#
# authors: swizzin gang
# #shellcheck source=sources/functions/sources
# . "/etc/swizzin/sources/functions/sources" utils os ip

for target in "${@}"; do
    if [[ -f "/etc/swizzin/sources/functions/${target}" ]]; then
        source "/etc/swizzin/sources/functions/${target}"
    fi
done
