#!/bin/bash

function create_self_ssl() {
    user=$1
    if [[ ! -f /home/$user/.ssl/$user-self-signed.key ]]; then
        echo_progress_start "Generating self-signed key for $user"
        mkdir -p /home/$user/.ssl
        country=US
        state=California
        locality="San Fransisco"
        organization=swizzin
        organizationalunit=$user
        commonname=$user
        ssl_password=""

        openssl genrsa -out "/home/$user/.ssl/$user-self-signed.key" 2048 >> /dev/null 2>&1
        openssl req -new -key /home/$user/.ssl/$user-self-signed.key -out /home/$user/.ssl/$user-self-signed.csr -passin pass:$ssl_password -subj "/C=$country/ST=$state/L=$locality/O=$organization/OU=$organizationalunit/CN=$commonname" >> /dev/null 2>&1
        openssl x509 -req -days 1095 -in "/home/$user/.ssl/$user-self-signed.csr" -signkey "/home/$user/.ssl/$user-self-signed.key" -out "/home/$user/.ssl/$user-self-signed.crt" >> /dev/null 2>&1
        chown -R $user: /home/$user/.ssl
        chmod 750 /home/$user/.ssl
        echo_progress_done "Key for $user generated"
    fi
}
