#!/usr/bin/env bash

export dbdir="/var/lib/swizzin/db"
export separator=" ==>>=>=> "

# Get a value from the database
# \
# $1 = key
# \
# **Returns code 1 if not found**
getswizdb() {
    key="$1"
    if [ -e "$dbdir/$key" ]; then
        echo_log_only "Found line $key"
        cat "$dbdir/$key"
        return 0
    else
        echo_log_only "Key \"$key\" not set"
        return 1
    fi
}
export -f getswizdb

_dropswizkey() {
    echo_log_only "Dropping key \"$1\""
    rm "$dbdir/$key"
}
export -f _dropswizkey

#Clear a value in the "database"
# \
# $1 = key
# \
# **Returns code 1 if not found**
clearswizdb() {
    key="$1"
    if getswizdb "$key" > /dev/null; then
        _dropswizkey "$key"
    else
        return 1
    fi
}
export -f clearswizdb

# Set a value in the database
# \
# $1 = key
# $2 = value
setswizdb() {
    mkdir -p $dbdir
    key="$1"
    value="$2"
    echo_log_only "Setting \"$key\" to \"$value\""
    echo "${value}" > "$dbdir/$key"
}
export -f setswizdb
