#!/bin/bash

function _get_user_password () {
    user_to_get="$1"
    password=''

    ##TODO fix when there is no addition users other than .master. It works but it's just ugly
    for file in /root/*.info /root/.master.info; do 
        user_in_file=$(cat $file | cut -d: -f1)
        if [ "$user_in_file" = "$user_to_get" ]; then 
            password="$(cat $file | cut -d: -f2)"
        fi
    done
    
    if [[ -z $password ]]; then 
        return 1
    fi
    echo $password
}
