#!/bin/bash
# Author Flying_sausages for Swizzin 2020

function _get_next_port_from_json () {
    key="$1"
    path=".config/transmission-daemon/settings.json"
    highestvalue=0

    for d in /home; do
         value=$(grep "$key" "$fullpath" | tr -d -c 0-9)
         if [[ $value > $highestvalue ]]; then 
            highestvalue=$value
         fi
    done

    [[ $highestvalue = 0 ]] && highestvalue=9091

    highestvalue+=1
    echo "$highestvalue"
}


function _getversion () {
    if [[ -z $arg_transmissionsource ]]; then
        
        if [[ "ubuntu" = true ]]; then 
            version=$(whiptail --title "Install Software" --menu "Choose which source to install Transmission from" --ok-button "Continue" --nocancel 10 50 2 \
                  PPA "(Directly from Transmission)" \
                  Repo "(Packaged and tested by Ubuntu)" \
                   3>&1 1>&2 2>&3)
        else
            version="Repo"
        fi
        export version
    fi

}

function _install () {
    _getversion
    if [[ $version = "PPA" ]]; then 
        if [[ "ubuntu" = false ]]; then 
            echo "PPA not available on this system, exiting"
            exit 1
        fi
        add-apt-repository ppa:transmissionbt/ppa
    fi
    echo "Fetching updates"
    apt-get update
    echo "Installing Transmission"
    apt-get install transmission-cli transmission-common transmission-daemon
    systemctl disable --now transmission-daemon
    
}

