#!/bin/bash
# Author Flying_sausages for Swizzin 2020

function _get_next_port_from_json() {
    key="$1"
    defaultport="$2"
    relpath=".config/transmission-daemon/settings.json"
    highestvalue=$defaultport
    wasincreased='false'

    for d in /home/*/; do
        value=""
        confpath="${d}${relpath}"
        if [[ -f $confpath ]]; then
            paramrr=".[\"$key\"]"
            value=$(jq -r "$paramrr" < "$confpath")
        fi
        if [[ -n $value ]]; then
            if [[ $value -ge $highestvalue ]]; then
                highestvalue=$value
                wasincreased='true'
            fi
        fi
    done

    if [[ $wasincreased = 'true' ]]; then
        ((highestvalue++))
    fi

    echo "$highestvalue"
}

function whiptail_transmission_source() {
    if [[ -z $TRANSMISSION_SOURCE ]]; then
        distribution=$(lsb_release -is)
        if [[ $distribution =~ "Ubuntu" ]]; then
            TRANSMISSION_SOURCE=$(whiptail --title "Install Software" --menu "Choose which source to install Transmission from" --ok-button "Continue" --nocancel 10 50 2 \
                PPA "(Directly from Transmission)" \
                Repo "(Packaged and tested by Ubuntu)" \
                3>&1 1>&2 2>&3)
        else
            TRANSMISSION_SOURCE="Repo"
        fi
        echo_log_only "TRANSMISSION_SOURCE = $TRANSMISSION_SOURCE"
        export TRANSMISSION_SOURCE
    fi

}

function _install_transmission() {
    whiptail_transmission_source
    distribution=$(lsb_release -is)
    if [[ $TRANSMISSION_SOURCE = "PPA" ]]; then
        if [[ ! $distribution =~ 'Ubuntu' ]]; then
            echo_warn "PPA not available on this system, using normal repo."
            return 1
        else
            echo_progress_start "Adding Transmission PPA"
            add-apt-repository ppa:transmissionbt/ppa -y >> "$log" 2>&1
            echo_progress_done "PPA Added"
        fi
    fi
    apt_install transmission-cli transmission-common transmission-daemon
    echo_progress_start "Disabling default non-multiuser service"
    systemctl disable -q --now transmission-daemon >> "$log" 2>&1
    echo_progress_done
}
