#!/bin/bash
#
# [swizzin :: box management solution]
# `box -h` for commands and info
#
# Author             :   swizzin | liara
#
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################

function _intro() {
  whiptail --title "Swizzin Package Manager" --msgbox "Welcome to the Box! Using this script you can choose to install and remove the packages contained within the package repository. Use the arrow keys to navigate, spacebar to toggle the currently selected item and enter to continue." 15 50
}

function _function() {
  function=$(whiptail --title "Swizzin" --menu "Choose an option:" --ok-button "Continue" --nocancel 12 50 3 \
               Install "packages" \
               Remove "packages" \
               Exit "" 3>&1 1>&2 2>&3)

    if [[ $function == Install ]]; then
      _install
    elif [[ $function == Remove ]]; then
      _remove
    elif [[ $function == Exit ]]; then
      exit 0
    fi
}

function _install() {
  installa=()
  locks=($(find /usr/local/bin/swizzin/install -type f -printf "%f\n" | cut -d "." -f 1 | sort -d))
  for i in "${locks[@]}"; do
    app=${i}
    if [[ ! -f /install/.$app.lock ]]; then
      installa+=("$i" '""')
    fi
  done
  whiptail --title "Install Software" --checklist --noitem --separate-output "Make some choices:" 15 26 7 "${installa[@]}" 2>results
  
  readarray result < results
  for i in "${result[@]}"; do
    result=$(echo $i)
    echo -e "Installing ${result}"
    bash /usr/local/bin/swizzin/install/${result}.sh
  done

   rm results
  _function
}

function _remove() {
removea=()
locks=($(find /usr/local/bin/swizzin/remove -type f -printf "%f\n" | cut -d "." -f 1 | sort -d))
for i in "${locks[@]}"; do
  app=${i}
  if [[ -f /install/.$app.lock ]]; then
    removea+=("$i" '""')
  fi
done
whiptail --title "Remove Software" --noitem --checklist --separate-output "Make some choices:" 15 26 7 "${removea[@]}" 2>results
  readarray result < results
  for i in "${result[@]}"; do
    result=$(echo $i)
    echo -e "Removing ${result}"
    bash /usr/local/bin/swizzin/remove/${result}.sh
  done
rm results
_function
}

function _cli() {
  arg=("$@")
  packages=("${arg[@]:1}")
  repo=($(find /usr/local/bin/swizzin/install -type f -printf "%f\n" | cut -d "." -f 1))
  for i in "${packages[@]}"; do
    app=${i}
    if [[ -f /install/.${app}.lock ]]; then
      echo -e "Package $i already installed"
    else
      if [[ "${repo[*]}" =~ $i ]]; then
        echo -e "Installing $i "
        bash /usr/local/bin/swizzin/install/$i.sh
      else
        echo -e "Package $i not found"
      fi
    fi
  done
}

function _clr() {
  arg=("$@")
  packages=("${arg[@]:1}")
  for i in "${packages[@]}"; do
    app=${i}
    if [[ -f /install/.$app.lock ]]; then
      echo -e "Removing $i "
      bash /usr/local/bin/swizzin/remove/$i.sh
    else
      echo -e "Package $i not installed"
    fi
  done
}

function _update() {
  echo -e "Updating swizzin local repository"
  cd /etc/swizzin
  git checkout master
  git fetch origin master
  git reset --hard origin/master
  #git pull
  chmod -R 700 /etc/swizzin/scripts
  for f in /etc/swizzin/scripts/update/*; do . $f; done
}

function _upgrade() {
  arg=("$@")
  packages=("${arg[@]:1}")
  repo=($(find /usr/local/bin/swizzin/upgrade -type f -printf "%f\n" | cut -d "." -f 1))
  for i in "${packages[@]}"; do
    app=${i}
    if [[ "${repo[*]}" =~ $i ]]; then
      echo -e "Upgrading $i "
      bash /usr/local/bin/swizzin/upgrade/$i.sh
    else
      echo -e "Upgrade script for $i does not exist"
    fi
  done
}

function _help() {
  sgformat="${bold}%-15s${normal}"
  spacing=$(echo $'\t' | pr -Te15)

  echo -e "Usage: `basename $0` [ install | remove | upgrade ] ${bold}pkg1 pkg2 [...]${normal}\n"
  echo -e "       `basename $0` [ adduser | deluser | chpasswd ] ${bold}username${normal}\n"
  echo -e "       `basename $0` [ list | update ]\n"
  echo -e "       `basename $0` panel fix-disk [ root | home ]\n"
  echo -e "       `basename $0`\n"
  echo -e "Note: Only install and remove functions accept package arguments. List and update must be run without modifiers\n" | fmt --goal=66 --tagged-paragraph
  echo -e "\n"
  printf "${sgformat}" "install"
  echo -e "The install function requires at least one package name as an argument but will accept multiples\n" | fmt --goal=50 | sed -e "2,\$s/^/$spacing/"
  echo -e "               Example: box install quassel syncthing znc\n" | fmt --goal=50 | sed -e "2,\$s/^/$spacing/"
  printf "${sgformat}" "remove"
  echo -e "The remove function requires at least one package name as an argument but will accept multiples\n" | fmt --goal=50 | sed -e "2,\$s/^/$spacing/"
  echo -e "               Example: box remove quassel syncthing znc\n" | fmt --goal=50 | sed -e "2,\$s/^/$spacing/"
   printf "${sgformat}" "adduser"
  echo -e "The adduser function requires a single user to be specified, this user will be created\n" | fmt --goal=50 | sed -e "2,\$s/^/$spacing/"
  echo -e "               Example: box adduser freeloadingfriend\n" | fmt --goal=50 | sed -e "2,\$s/^/$spacing/"
   printf "${sgformat}" "deluser"
  echo -e "The deluser function requires a single user to be specified, this user will be removed\n" | fmt --goal=50 | sed -e "2,\$s/^/$spacing/"
  echo -e "               Example: box deluser exgirlfriend\n" | fmt --goal=50 | sed -e "2,\$s/^/$spacing/"
   printf "${sgformat}" "chpasswd"
  echo -e "The chpasswd function requires a single user to be specified, their password will be changed\n" | fmt --goal=50 | sed -e "2,\$s/^/$spacing/"
  echo -e "               Example: box chpasswd forgetfulfriend\n" | fmt --goal=50 | sed -e "2,\$s/^/$spacing/"
  printf "${sgformat}" "update"
  echo -e "The update command will update your local swizzin repository to the latest version and run important update scripts\n" | fmt --goal=50 | sed -e "2,\$s/^/$spacing/"
  printf "${sgformat}" "upgrade"
  echo -e "Runs the associated upgrade script.\n" | fmt --goal=50 | sed -e "2,\$s/^/$spacing/"
  printf "${sgformat}" "panel fix-disk"
  echo -e "The panel fix-disk command change the disk widget in the web panel to root or home\n" | fmt --goal=50 | sed -e "2,\$s/^/$spacing/"
  printf "${sgformat}" "list"
  echo -e "The list command will list packages available to be managed by box\n" | fmt --goal=50 | sed -e "2,\$s/^/$spacing/"
}

function _list() {
  repo=($(find /usr/local/bin/swizzin/install -type f -printf "%f\n" | cut -d. -f 1 | sort -d))
  if [[ -f /srv/panel/inc/localize.php ]]; then
    lang=$(grep language /srv/panel/inc/localize.php | cut -d "'" -f 2)
    locale=/srv/panel/lang/$lang
  else
    locale=/etc/swizzin/sources/lang_en
  fi
  for i in "${repo[@]}"; do
    app=$i
    if [[ $i == ombi ]]; then app=ombi; fi
    sgformat="${bold}%-15s${normal}"
    spacing=$(echo $'\t' | pr -Te15)
    description=$(grep -i -m 1 \\\[\'$app $locale | cut -d= -f2 | sed "s/ '//g" | sed "s/';//g" | sed "s/\\\'/'/g")
    if [[ -z $description ]]; then description="Description missing";fi
    printf "${sgformat}" "$i"
    echo -e "${description}\n" | fmt --goal=50 | sed -e "2,\$s/^/$spacing/"

  done
}

function _adduser {
  user=$2
  if [[ $user =~ [A-Z] ]]; then
    echo "Usernames must not contain capital letters. Please try again."
    exit 1
  fi

  if [[ -f /root/${user}.info ]]; then
    echo "User already seems to exist"
    exit 1
  fi

  id -u ${user} > /dev/null 2>&1
  existing=$?

  if [[ $existing == 0 ]]; then
    echo "${user} already appears to be present on this machine; however, it does not appear to be configured as a swizzin user"
    echo
    read -rep 'Press enter to continue adding user.'
    echo
  fi

  echo -e "Enter password for ${user}. (leave empty to generate a password)"; read 'pass'

  if [[ -z "${pass}" ]]; then
    pass="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c16)"
    echo "Password for ${user} has been set to ${pass}"
  fi
  if [[ -n $(which cracklib-check) ]]; then 
    echo "Cracklib detected. Checking password strength."
    sleep 1
    str="$(cracklib-check <<<"$pass")"
    check=$(grep OK <<<"$str")
    if [[ -z $check ]]; then
      read -n 1 -s -r -p "Password did not pass cracklib check. Press any key to enter a new password"
      printf "\n"
      _adduser "$@"
    else
      echo "OK"
    fi
  fi
  echo "$user:$pass" > /root/${user}.info
  if [[ $existing == 1 ]]; then
    useradd "${user}" -m -G www-data -s /bin/bash
  fi
  chpasswd<<<"${user}:${pass}"
  htpasswd -b /etc/htpasswd $user $pass
  mkdir -p /etc/htpasswd.d/
  htpasswd -b -c /etc/htpasswd.d/htpasswd.${user} $user $pass
  chmod 750 /home/${user}

  if [[ -f /install/.quota.lock ]]; then 
    setdisk "$user"
  fi

  if [[ -f /install/.panel.lock ]]; then setfacl -m g:swizzin:rx /home/${user}; fi
  echo "D /var/run/${user} 0750 ${user} ${user} -" >> /etc/tmpfiles.d/${user}.conf
  systemd-tmpfiles /etc/tmpfiles.d/${user}.conf --create

  for app in rtorrent rutorrent deluge autodl flood nzbget lounge transmission organizr; do
    if [[ $app = "rutorrent" ]]; then
      if [[ -d /srv/rutorrent ]]; then
        if [[ ! -f /install/.rutorrent.lock ]]; then touch /install/.rutorrent.lock; fi
      fi
    fi

    if [[ -f /install/.${app}.lock ]]; then
      if [[ $app = "flood" ]]; then
        /usr/local/bin/swizzin/install/${app}.sh
      elif [[ $app = "organizr" ]]; then
        #TODO fix when organizr API can do this
        echo "Please add the user to organizr manually"
      else
        /usr/local/bin/swizzin/install/${app}.sh ${user}
        if [[ $app = "deluge" ]]; then
          /usr/local/bin/swizzin/nginx/deluge.sh ${user}
          app="{deluged,deluge-web}"
          eval systemctl enable ${app}@${user}
          eval systemctl start ${app}@${user}
        elif [[ $app =~ ("rutorrent"|"lounge") ]]; then
          :
        else
          if [[ $app = "autodl" ]]; then app=irssi; fi
          systemctl enable ${app}@${user}
          systemctl start ${app}@${user}
        fi
      fi
    fi
  done

  USER=${user^^}
  cat > /etc/sudoers.d/${user} <<SUD
Cmnd_Alias   ${USER}CMDS = /bin/systemctl stop flood@${user}, /bin/systemctl restart flood@${user}, /bin/systemctl start flood@${user}, /bin/systemctl start rtorrent@${user}, /bin/systemctl stop rtorrent@${user}, /bin/systemctl restart rtorrent@${user}, /bin/systemctl start deluged@${user}, /bin/systemctl stop deluged@${user}, /bin/systemctl restart deluged@${user}, /bin/systemctl start deluge-web@${user}, /bin/systemctl stop deluge-web@${user}, /bin/systemctl restart deluge-web@${user}, /bin/systemctl start irssi@${user}, /bin/systemctl stop irssi@${user}, /bin/systemctl restart irssi@${user}, /usr/local/bin/swizzin/box chpasswd ${user}

${user}     ALL = (ALL) NOPASSWD: ${USER}CMDS
SUD
if [[ -f /install/.nginx.lock ]]; then
  systemctl reload nginx
fi

#echo "export PATH=$PATH:/usr/local/bin/swizzin" >> /home/$user/.profile
#chown $user: /home/$user/.profile
}

function _deluser {
  user=$2
  if [[ ! -f /root/${user}.info ]]; then
    master=$(cut -d: -f1 < /root/.master.info)
    if [[ $user == $master ]]; then
      echo "Master user deletion is not supported"
      exit 1
    fi
    echo "Error: user ${user} not found. Exiting."
    exit 1
  fi

  echo "WARNING: This will delete the user '${user}' and all associated configs and subdirectories. THIS ACTION CANNOT BE UNDONE."
  echo
  read -rep 'Removal will start as soon as you confirm this message. Press enter to continue.'
  
  for app in rtorrent rutorrent deluge autodl flood nzbget lounge organizr transmission; do
    if [[ $app = "rutorrent" ]]; then
      if [[ -d /srv/rutorrent ]]; then
        if [[ ! -f /install/.rutorrent.lock ]]; then touch /install/.rutorrent.lock; fi
      fi
    fi

    if [[ -f /install/.${app}.lock ]]; then
      if [[ $app = "rutorrent" ]]; then
        rm -rf /srv/rutorrent/conf/users/${user}
        rm -rf /srv/rutorrent/share/users/${user}
        rm -f /etc/nginx/apps/${user}*
      elif [[ $app = "lounge" ]]; then
        su -s /bin/sh lounge -c "thelounge remove ${user}" > /dev/null
      elif [[ $app = "deluge" ]]; then
        app="{deluged,deluge-web}"
        rm -rf /etc/nginx/conf.d/${user}.deluge.conf
        eval systemctl disable ${app}@${user}
        eval systemctl stop ${app}@${user}
      elif [[ $app == "autodl" ]]; then
        systemctl disable --now irssi@${user}
      else
        systemctl disable ${app}@${user}
        systemctl stop ${app}@${user}
      fi
    fi
  done
  
  if [[ -z $(which lsof) ]]; then
    apt-get install -y -q lsof > /dev/null 2>&1
  fi

  kill -9 $(lsof -t /home/${user})
  deluser --force --remove-home ${user}
  groupdel ${user}
  rm -f /etc/htpasswd.d/htpasswd.${user}
  htpasswd -D /etc/htpasswd ${user}
  rm -f /etc/tmpfiles.d/${user}.conf
  rm -f /etc/nginx/conf.d/${user}*
  rm -f /etc/sudoers.d/${user}
  rm -rf /run/screen/S-${user}
  rm -rf /var/run/${user}
  rm -rf /home/${user}
  rm /root/${user}.info
  systemctl reload nginx
}

function _chpasswd {
  user=$2
  echo -e "Enter new password for ${user}. Leave empty to generate a password"; read 'pass'
  if [[ -z "${pass}" ]]; then
    pass="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c16)"
    echo "New password has been set to ${pass}"
  fi
  if [[ -n $(which cracklib-check) ]]; then 
    echo "Cracklib detected. Checking password strength."
    sleep 1
    str="$(cracklib-check <<<"$pass")"
    check=$(grep OK <<<"$str")
    if [[ -z $check ]]; then
      read -n 1 -s -r -p "Password did not pass cracklib check. Press any key to enter a new password"
      printf "\n"
      _chpasswd "$@"
    else
      echo "OK"
    fi
  fi
  master=$(cut -d: -f1 < /root/.master.info)
  if [[ $user = $master ]]; then
    echo "$user:$pass" > /root/.master.info
  fi
  echo "$user:$pass" > /root/${user}.info
  chpasswd<<<"${user}:${pass}"
  htpasswd -b /etc/htpasswd $user $pass
  mkdir -p /etc/htpasswd.d/
  htpasswd -b -c /etc/htpasswd.d/htpasswd.${user} $user $pass
  if [[ -e /install/.deluge.lock ]]; then
    systemctl stop deluged@${user}
    systemctl stop deluge-web@${user}
    DWSALT=$(tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 32 | head -n 1)
    DWP=$(python2 /usr/local/bin/swizzin/deluge.Userpass.py ${pass} ${DWSALT})
    sed -i "s/.*${user}.*/${user}:${pass}:10/" /home/$user/.config/deluge/auth
    sed -i "s/.*pwd_salt.*/  \"pwd_salt\": \"${DWSALT}\",/" /home/$user/.config/deluge/web.conf
    sed -i "s/.*pwd_sha1.*/  \"pwd_sha1\": \"${DWP}\",/" /home/$user/.config/deluge/web.conf
    sed -i "/$user/{n;s/.*/      \"${pass}\"/}" /home/${user}/.config/deluge/hostlist.conf.1.2
    systemctl start deluged@${user}
    systemctl start deluge-web@${user}
  fi

  if [[ -e /install/.transmission.lock ]]; then 
    systemctl stop transmission@${user}
    sed -i "s/.*rpc-password.*/  \"rpc-password\": \"${pass}\",/" /home/$user/.config/transmission-daemon/settings.json
    systemctl start transmission@${user}
  fi
  if [[ -f /install/.lounge.lock ]]; then 
    su -s /bin/sh lounge -c "thelounge reset $user " <<< "${pass}" > /dev/null
  fi
  if [[ -f /install/.organizr.lock ]]; then 
    #TODO fix when API allows to
    echo "Your organizr password has not yet been changed, please do so manually"
  fi

}

function _nukeovh() {
  grsec=$(uname -a | grep -i grs)
  if [[ -n $grsec ]]; then
    echo
    echo -e "Your server is currently running with kernel version: $(uname -r)"
    echo -e "While not it is not required to switch, kernels with grsec are not recommend due to conflicts in the panel and other packages."
    echo
    echo -ne "Would you like swizzin to install the distribution kernel? (Default: Y) "; read input
      case $input in
        [yY] | [yY][Ee][Ss] | "" ) kernel=yes; echo "Your distribution's default kernel will be installed. You will need to reboot after these changes."  ;;
        [nN] | [nN][Oo] ) echo "Why did you even run this function?" exit 1 ;;
      *) kernel=yes; echo "Your distribution's default kernel will be installed. You will need to reboot after these changes."  ;;
      esac
      if [[ $kernel == yes ]]; then
        if [[ $DISTRO == Ubuntu ]]; then
          apt-get install -q -y linux-image-generic >>"${OUTTO}" 2>&1
        elif [[ $DISTRO == Debian ]]; then
          arch=$(uname -m)
          if [[ $arch =~ ("i686"|"i386") ]]; then
            apt-get install -q -y linux-image-686 >>"${OUTTO}" 2>&1
          elif [[ $arch == x86_64 ]]; then
            apt-get install -q -y linux-image-amd64 >>"${OUTTO}" 2>&1
          fi
        fi
        mv /etc/grub.d/06_OVHkernel /etc/grub.d/25_OVHkernel
        update-grub >>"${OUTTO}" 2>&1
      fi
    else
    echo
    echo -e "grsec not detected. Nothing to do."
  fi
}

normal=$(tput sgr0)
yellow=$(tput setaf 3)
bold=$(tput bold)

case "$1" in
  "")
    _intro
    _function
    exit 0
  ;;
  "help"|"-h")
    _help "$0"
    exit 0
  ;;
  "install"|"it")
    if [[ -z $2 ]]; then
      echo "Error: You must choose some packages"
      exit 1
    fi
    _cli "$@"
    exit 0
  ;;
  "remove"|"rm")
    if [[ -z $2 ]]; then
      echo "Error: You must choose some packages"
      exit 1
    fi
    _clr "$@"
    exit 0
  ;;
  "adduser")
    if [[ -z $2 ]]; then
      echo "Error: You must specify a user"
      exit 1
    fi
    if [[ -n $3 ]]; then
      echo -e "Error: too many arguments\nCorrect usage: box adduser <username>"
      exit 1
    fi
  _adduser "$@"
  exit 0
  ;;
  "deluser")
    if [[ -z $2 ]]; then
      echo -e "Error: you must specify a username.\nCorrect usage: box deluser <username>"
      exit 1
    fi
    if [[ -n $3 ]]; then
      echo -e "Error: too many arguments\nCorrect usage: box deluser <username>"
      exit 1
    fi
    _deluser "$@"
    exit 0
  ;;
  "chpasswd")
    if [[ -n $3 ]]; then
      echo -e "Error: too many arguments\nCorrect usage: box chpasswd <username>"
      exit 1
    fi
    _chpasswd "$@"
    exit 0
  ;;
  "rmgrsec")
    _nukeovh
    exit 0
  ;;
  "rtx")
    /usr/local/bin/swizzin/rtx
  ;;
  "update")
    _update
    exit 0
  ;;
  "upgrade")
    if [[ ! $2 ]]; then echo "You must choose at least one package to update."; exit 1; fi
    _update
    _upgrade "$@"
    exit 0
  ;;
  "list")
    _list
    exit 0
  ;;
  *)
    echo "Error: $1 invalid command"
    exit 1
  ;;
esac

