#!/bin/bash
# ruTorrent e(x)tras management

function _check_for_rutorrent() {
    if [ ! -f "/install/.rutorrent.lock" ]; then
        echo_error "ruTorrent is not installed. Try installing ruTorrent first."
        exit 1
    fi
}
. /etc/swizzin/sources/globals.sh
. /etc/swizzin/sources/functions/rutorrent
_check_for_rutorrent

function _intro() {
    whiptail --title "ruTorrent Extras Manager" --msgbox "Welcome to rtx! Using this script you can choose to install and remove the plugins and themes for ruTorrent. Use the arrow keys to navigate, spacebar to toggle the currently selected item and enter to continue." 15 50
}

function _function() {
    function=$(whiptail --title "rtx" --menu "Choose an option:" --ok-button "Continue" --nocancel 12 50 3 \
        Plugins "" \
        Themes "" \
        Exit "" 3>&1 1>&2 2>&3)

    case $function in
        Plugins)
            _plugins
            ;;
        Themes)
            _themes
            ;;
        Exit)
            exit 0
            ;;
        *) ;;
    esac
}

function _plugins() {
    function=$(whiptail --title "rtx" --menu "Choose an option:" --ok-button "Continue" --nocancel 12 50 4 \
        Install "plugins" \
        Remove "plugins" \
        Back "" \
        Exit "" 3>&1 1>&2 2>&3)

    case $function in
        Install)
            _itplugs
            ;;
        Remove)
            _rmplugs
            ;;
        Back)
            _function
            ;;
        Exit)
            exit 0
            ;;
        *) ;;
    esac
}

function _themes() {
    function=$(whiptail --title "rtx" --menu "Choose an option:" --ok-button "Continue" --nocancel 12 50 4 \
        Install "themes" \
        Remove "themes" \
        Back "" \
        Exit "" 3>&1 1>&2 2>&3)

    case $function in
        Install)
            _itthemes
            ;;
        Remove)
            _rmthemes
            ;;
        Back)
            _function
            ;;
        Exit)
            exit 0
            ;;
        *) ;;
    esac
}

function _itplugs() {
    arg=("$@")
    result=("${arg[@]:1}")
    tag=$(git -C /srv/rutorrent describe --tags | grep -oP 'v\d\.\d+(\-beta\.?\d?+)?(\.?\d+?)?([^-]?)')
    installa=()
    plugs=(_getdir _noty _noty2 _task autotools check_port chunks cookies cpuload create data datadir diskspace edit erasedata extratio extsearch feeds filedrop filemanager filemanager-media filemanager-share geoip history httprpc ipad loginmgr lookat mediainfo mobile pausewebui ratio ratiocolor retrackers rpc rss rssurlrewrite rutracker_check scheduler screenshots seedingtime show_peers_like_wtorrent source spectrogram theme throttle tracklabels trafic unpack uploadeta xmpp)

    # This plugin won't work before v4
    if [[ $tag =~ ^v3 ]]; then
        plugs=("${plugs[@]/filemanager-media/}")
    fi

    # Dynamically create whiptail options:
    # Don't offer to install installed plugins
    for i in "${plugs[@]}"; do
        plug=${i}
        if [[ ! -d /srv/rutorrent/plugins/${plug} ]]; then
            installa+=("$i" '""')
        fi
    done
    if [[ -z $result ]]; then
        whiptail --title "Choose Plugins" --checklist --noitem --separate-output "Make some choices:" 15 46 7 "${installa[@]}" 2> /tmp/results

        exitstatus=$?
        if [[ $exitstatus = "1" ]]; then
            _plugins
        fi

        readarray -t result < /tmp/results
    fi
    for result in "${result[@]}"; do
        echo_info "Installing ${result}"
        cd /srv/rutorrent/plugins
        case "$result" in
            _getdir | _noty | _noty2 | _task | autotools | check_port | chunks | cookies | cpuload | create | data | datadir | diskspace | edit | erasedata | extratio | extsearch | feeds | filedrop | geoip | history | httprpc | ipad | loginmgr | lookat | mediainfo | ratio | retrackers | rpc | rss | rssurlrewrite | rutracker_check | scheduler | screenshots | seedingtime | show_peers_like_wtorrent | source | spectrogram | theme | throttle | tracklabels | trafic | unpack | uploadeta | xmpp)
                svn co https://github.com/Novik/ruTorrent.git/tags/${tag}/plugins/${result} ${result}
                case $result in
                    create)
                        sed -i 's/useExternal = false;/useExternal = "mktorrent";/' /srv/rutorrent/plugins/create/conf.php
                        sed -i 's/pathToCreatetorrent = '\'\''/pathToCreatetorrent = '\''\/usr\/bin\/mktorrent'\''/' /srv/rutorrent/plugins/create/conf.php
                        ;;
                    diskspace)
                        rutorrent_fix_quota
                        ;;

                    ipad)
                        if [[ -d /srv/rutorrent/plugins/mobile ]]; then
                            echo_warn "iPad plugin is not compatible with mobile"
                            continue
                        fi
                        ;;

                    spectrogram)
                        apt-get -y -q install sox > /dev/null 2>&1
                        sed -i "s/\$pathToExternals\['sox'\] = ''/\$pathToExternals\['sox'\] = '\/usr\/bin\/sox'/g" /srv/rutorrent/plugins/spectrogram/conf.php
                        ;;

                    *) ;;

                esac
                ;;
            filemanager)
                case $tag in
                    3.*)
                        svn co https://github.com/nelu/rutorrent-thirdparty-plugins/trunk/filemanager > /dev/null 2>&1
                        chmod -R +x /srv/rutorrent/plugins/filemanager/scripts
                        cat > /srv/rutorrent/plugins/filemanager/conf.php << FMCONF
<?php
\$fm['tempdir'] = '/tmp';
\$fm['mkdperm'] = 755;
// set with fullpath to binary or leave empty
\$pathToExternals['rar'] = '$(which rar)';
\$pathToExternals['zip'] = '$(which zip)';
\$pathToExternals['unzip'] = '$(which unzip)';
\$pathToExternals['tar'] = '$(which tar)';
// archive mangling, see archiver man page before editing
\$fm['archive']['types'] = array('rar', 'zip', 'tar', 'gzip', 'bzip2');
\$fm['archive']['compress'][0] = range(0, 5);
\$fm['archive']['compress'][1] = array('-0', '-1', '-9');
\$fm['archive']['compress'][2] = \$fm['archive']['compress'][3] = \$fm['archive']['compress'][4] = array(0);
?>
FMCONF
                        ;;
                    v4.0-beta.1)
                        git clone https://github.com/nelu/rutorrent-filemanager filemanager >> /dev/null 2>&1
                        git -C /srv/rutorrent/plugins/filemanager checkout 234f5f20841ad3d1e3c095e6c6954a875fc8a6ea >> /dev/null 2>&1
                        ;;
                    *)
                        git clone https://github.com/nelu/rutorrent-filemanager filemanager >> /dev/null 2>&1
                        ;;
                esac
                ;;
            filemanager-share)
                case $tag in
                    3.*)
                        svn co https://github.com/nelu/rutorrent-thirdparty-plugins/trunk/fileshare > /dev/null 2>&1
                        ln -s /srv/rutorrent/plugins/fileshare/share.php /srv/fancyindex/share.php > /dev/null 2>&1
                        sed -i 's/$downloadpath .*/$downloadpath = '"'https:\/\/'"'.$_SERVER['"'HTTP_HOST'"'] . '"'\/fancyindex\/share.php'"';/g' /srv/rutorrent/plugins/fileshare/conf.php
                        ;;
                    v4.0-beta.1)
                        git clone https://github.com/nelu/rutorrent-filemanager-share.git filemanager-share > /dev/null 2>&1
                        git -C /srv/rutorrent/plugins/filemanager-share checkout 08abb838ec1e76d59051e3da5f3be69afeef31a1 > /dev/null 2>&1
                        ln -s /srv/rutorrent/plugins/filemanager-share/share.php /srv/fancyindex/share.php > /dev/null 2>&1
                        sed -i 's/$downloadpath .*/$downloadpath = '"'https:\/\/'"'.$_SERVER['"'HTTP_HOST'"'] . '"'\/fancyindex\/share.php'"';/g' /srv/rutorrent/plugins/filemanager-share/conf.php
                        ;;
                    *)
                        git clone https://github.com/nelu/rutorrent-filemanager-share.git filemanager-share > /dev/null 2>&1
                        ln -s /srv/rutorrent/plugins/filemanager-share/share.php /srv/fancyindex/share.php > /dev/null 2>&1
                        sed -i 's/$downloadpath .*/$downloadpath = '"'https:\/\/'"'.$_SERVER['"'HTTP_HOST'"'] . '"'\/fancyindex\/share.php'"';/g' /srv/rutorrent/plugins/filemanager-share/conf.php
                        ;;
                esac

                ;;
            filemanager-media)
                case $tag in
                    v4.0-beta.1)
                        git clone https://github.com/nelu/rutorrent-filemanager-media.git filemanager-media > /dev/null 2>&1
                        git -C /srv/rutorrent/plugins/filemanager-media checkout f1b92a1a9de1e81561877953a8599596510078d2 > /dev/null 2>&1
                        ln -s /srv/rutorrent/plugins/filemanager-media/stream.php /srv/fancyindex/stream.php > /dev/null 2>&1
                        sed -i 's/$streampath .*/$streampath = '"'https:\/\/'"'.$_SERVER['"'HTTP_HOST'"'] . '"'\/fancyindex\/stream.php'"';/g' /srv/rutorrent/plugins/filemanager-media/conf.php
                        ;;
                    *)
                        git clone https://github.com/nelu/rutorrent-filemanager-media.git filemanager-media > /dev/null 2>&1
                        ln -s /srv/rutorrent/plugins/filemanager-media/stream.php /srv/fancyindex/stream.php > /dev/null 2>&1
                        sed -i 's/$streampath .*/$streampath = '"'https:\/\/'"'.$_SERVER['"'HTTP_HOST'"'] . '"'\/fancyindex\/stream.php'"';/g' /srv/rutorrent/plugins/filemanager-media/conf.php
                        ;;
                esac
                ;;
            #fileupload)
            #svn co https://github.com/nelu/rutorrent-thirdparty-plugins/trunk/fileupload >/dev/null 2>&1
            #;;
            #logoff)
            #    wget -q https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/rutorrent-logoff/logoff-1.3.tar.gz
            #    tar xf logoff-1.3.tar.gz > /dev/null 2>&1
            #    rm -rf logoff-1.3.tar.gz
            #    ;;
            mobile)
                git clone https://github.com/xombiemp/rutorrentMobile.git mobile > /dev/null 2>&1
                rm -r /srv/rutorrent/plugins/ipad
                ;;
            pausewebui)
                git clone https://github.com/Gyran/rutorrent-pausewebui.git pausewebui > /dev/null 2>&1
                ;;
            ratiocolor)
                svn co https://github.com/Gyran/rutorrent-ratiocolor.git/trunk ratiocolor > /dev/null 2>&1
                sed -i "s/changeWhat = \"cell-background\";/changeWhat = \"font\";/g" /srv/rutorrent/plugins/ratiocolor/init.js
                ;;
            *)
                echo_error "$ is invalid"
                ;;
        esac
    done
    chown -R www-data: /srv/rutorrent/plugins
    /usr/local/bin/swizzin/php-fpm-cli -r 'opcache_reset();'
    if [[ -z $arg ]]; then
        rm /tmp/results
        _function
    fi
}

function _rmplugs() {
    arg=("$@")
    result=("${arg[@]:1}")
    removea=()
    plugs=(autotools checkport chunks cookies cpuload create data datadir diskspace edit erasedata extratio extsearch feeds filedrop filemanager filemanager-media filemanager-share fileshare fileupload geoip getdir history httprpc ipad loginmgr logoff lookat mediainfo mobile noty pausewebui ratio ratiocolor retrackers rpc rss rssurlrewrite rutracker_check scheduler screenshots seedingtime show_peers_like_wtorrent source spectrogram task theme throttle tracklabels trafic unpack uploadeta xmpp)

    # Dynamically create whiptail options:
    # Don't offer to remove plugins which aren't installed
    for i in "${plugs[@]}"; do
        plug=${i}
        if [[ -d /srv/rutorrent/plugins/$i ]]; then
            removea+=("$i" '""')
        fi
    done
    if [[ -z $result ]]; then
        whiptail --title "Choose Plugins" --noitem --checklist --separate-output "Make some choices:" 15 46 7 "${removea[@]}" 2> /tmp/results

        exitstatus=$?
        if [[ $exitstatus = "1" ]]; then
            _plugins
        fi

        readarray -t result < /tmp/results
    fi
    for result in "${result[@]}"; do
        echo_info "Removing ${result}"
        rm -rf /srv/rutorrent/plugins/${result}
        case $result in
            fileshare | filemanager-share)
                rm -f /srv/fancyindex/share.php
                ;;
            filemanager-media)
                rm -f /srv/fancyindex/stream.php
                ;;
            *) ;;
        esac
    done
    /usr/local/bin/swizzin/php-fpm-cli -r 'opcache_reset();'
    if [[ -z $arg ]]; then
        rm /tmp/results
        _function
    fi
}

function _itthemes() {
    arg=("$@")
    result=("${arg[@]:1}")
    installa=()
    themes=(Acid Agent34 Agent46 Blue club-QuickBox Dark DarkBetter Excel FlatUI_Dark FlatUI_Light FlatUI_Material MaterialDesign Oblivion OblivionBlue)

    # Dynamically create whiptail options:
    # Don't offer to install themes which are installed
    for theme in "${themes[@]}"; do
        plug=${theme}
        if [[ ! -d /srv/rutorrent/plugins/theme/themes/${theme} ]]; then
            installa+=("$theme" '""')
        fi
    done
    if [[ -z $result ]]; then
        whiptail --title "Choose Themes" --checklist --noitem --separate-output "Make some choices:" 15 46 7 "${installa[@]}" 2> /tmp/results

        exitstatus=$?
        if [[ $exitstatus = "1" ]]; then
            _themes
        fi

        readarray -t result < /tmp/results
    fi
    for result in "${result[@]}"; do
        echo_info "Installing ${result}"
        cd /srv/rutorrent/plugins/theme/themes
        case "$result" in
            Acid | Blue | Dark | DarkBetter | Excel | MaterialDesign | Oblivion)
                svn co https://github.com/Novik/ruTorrent.git/trunk/plugins/theme/themes/${result} ${result} > /dev/null 2>&1
                ;;
            Agent* | OblivionBlue)
                svn co https://github.com/ArtyumX/ruTorrent-Themes/trunk/${result} ${result} > /dev/null 2>&1
                ;;
            club-QuickBox)
                git clone https://github.com/QuickBox/club-QuickBox.git ${result} > /dev/null 2>&1
                ;;
            FlatUI*)
                svn co https://github.com/exetico/FlatUI.git/trunk/${result} ${result} > /dev/null 2>&1
                ;;
            *)
                echo_error "$result is invalid"
                ;;
        esac
    done
    chown -R www-data: /srv/rutorrent/plugins
    /usr/local/bin/swizzin/php-fpm-cli -r 'opcache_reset();'
    if [[ -z $arg ]]; then
        rm /tmp/results
        _function
    fi
}

function _rmthemes() {
    arg=("$@")
    result=("${arg[@]:1}")
    removea=()
    themes=(Acid Agent34 Agent46 Blue club-QuickBox Dark DarkBetter Excel FlatUI_Dark FlatUI_Light FlatUI_Material MaterialDesign Oblivion OblivionBlue)
    for i in "${themes[@]}"; do
        themes=${i}
        if [[ -d /srv/rutorrent/plugins/theme/themes/$i ]]; then
            removea+=("$i" '""')
        fi
    done
    if [[ -z $result ]]; then
        whiptail --title "Choose Themes" --noitem --checklist --separate-output "Make some choices:" 15 46 7 "${removea[@]}" 2> /tmp/results

        exitstatus=$?
        if [[ $exitstatus = "1" ]]; then
            _themes
        fi

        readarray -t result < /tmp/results
    fi
    for result in "${result[@]}"; do
        echo_info "Removing ${result}"
        rm -rf /srv/rutorrent/plugins/theme/themes/${result}
    done
    /usr/local/bin/swizzin/php-fpm-cli -r 'opcache_reset();'
    if [[ -z $arg ]]; then
        rm /tmp/results
        _function
    fi
}

case "$1" in
    "")
        _intro
        _function
        exit 0
        ;;
    "install-plugin" | "itp")
        if [[ -z $2 ]]; then
            echo_error "You must choose some plugins"
            exit 1
        fi
        _itplugs "$@"
        ;;
    "remove-plugin" | "rmp")
        if [[ -z $2 ]]; then
            echo_error "You must choose some plugins"
            exit 1
        fi
        _rmplugs "$@"
        ;;
    "install-theme" | "itt")
        if [[ -z $2 ]]; then
            echo_error "You must choose some themes"
            exit 1
        fi
        _itthemes "$@"
        ;;
    "remove-theme" | "rmt")
        if [[ -z $2 ]]; then
            echo_error "You must choose some themes"
            exit 1
        fi
        _rmthemes "$@"
        ;;
    *)
        echo_error "Invalid command: $1"
        exit 1
        ;;
esac
