#!/bin/bash
#
# [Quick Network Interface Input]
#
# GitHub:   https://github.com/QuickBox/QuickBox
# Author:   QuickBox.IO
# URL:      https://quickbox.io
#
# QuickBox Copyright (C) 2017 QuickBox.io
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#

ADAPT=$(cat /srv/panel/db/interface.txt);


sed -i "s/INETFACE/${ADAPT}/g" /srv/panel/widgets/stat.php;
sed -i "s/INETFACE/${ADAPT}/g" /srv/panel/widgets/data.php;
sed -i "s/INETFACE/${ADAPT}/g" /srv/panel/widgets/bw_tables.php;
sed -i "s/INETFACE/${ADAPT}/g" /srv/panel/inc/config.php;
