name: test-pull-request
on:
  - workflow_dispatch

jobs:
  build-latest:
    runs-on: ubuntu-latest
    name: Test pull request latest
    env:
      none: ""

    steps:
      - uses: actions/checkout@v2.3.4

      - name: download
        run: wget -qO swizzin.sh git.io/swizzin

      - name: download
        run: sudo bash swizzin.sh --user username --pass password --skip-cracklib --unattend

      - name: Install
        run: sudo box install calibreweb

      - name: Host - Upload artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: log
          path: /root/logs/swizzin.log

  build-18.04:
    runs-on: ubuntu-18.04
    name: Test pull request 18.04
    env:
      none: ""

    steps:
      - uses: actions/checkout@v2.3.4

      - name: download
        run: wget -qO swizzin.sh git.io/swizzin

      - name: download
        run: sudo bash swizzin.sh --user username --pass password --skip-cracklib --unattend

      - name: Install
        run: sudo box install calibreweb

      - name: Host - Upload artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: log
          path: /root/logs/swizzin.log
